#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down

# Start common applications
# polkit-gnome to manage user session
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &> /dev/null &

# polkit-kde to manage user session
/usr/lib/polkit-kde-authentication-agent-1 &> /dev/null &

# Kde autostart services
/usr/bin/kded5 &> /dev/null &

#volume icon
if [ -x "$(command -v volumeicon)" ]; then
  volumeicon &> /dev/null &
fi

# clipit
if [ -x "$(command -v klipper)" ]; then
  clipit &> /dev/null &
fi

#boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill --randomize $SCRIPTPATH/wallpapers/
fi

# extra utils to make this theme a little more homey
if [ -x "$(command -v dunst)" ]; then
  dunst -config ~/.config/dunst/dunstrc &
fi

#include desire.conf to kitty file, and make a symlink.
ln -s $SCRIPTPATH/kitty/desire.conf $HOME/.config/kitty
cd $HOME/.config/kitty
echo "include ./desire.conf" >> kitty.conf

#boot a polybar for each monitor
cd ${SCRIPTPATH}/polybar
polybar -m | sed s/:.*// | tac | while read -r monitor
do
  monitor=$monitor polybar -c config.ini main &> /tmp/polybar.log &
done

